export const initialState = {
  tasks: [
    {
      id: "abc123",
      title: "Design Landing Page",
      description: "Create wireframes and design mockups for the landing page.",
      startDate: "2024-04-22",
      status: "Pending",
      assignee: "John Doe",
      team: "abc",
      priority: "P1",
    },
    {
      id: "abc1234",
      title: "Design Landing Page",
      description: "Create wireframes and design mockups for the landing page.",
      startDate: "2024-04-02",
      status: "Pending",
      assignee: "Smith",
      team: "Falcon",
      priority: "P0",
    },
    {
      id: "abc12345",
      title: "Develop User Authentication",
      description: "Implement user authentication system using JWT.",
      startDate: "2024-03-24",
      status: "In Progress",
      assignee: "John Doe",
      team: "WebMaster",
      priority: "P0",
    },
    {
      id: "abc123456",
      title: "Fix Bug in Dashboard",
      description: "Resolve issue with data not loading.",
      startDate: "2024-04-22",
      endDate: "2024-03-25",
      status: "Completed",
      assignee: "Chris Johnson",
      team: "Coder",
      priority: "P2",
    },
    {
      id: "abc1234567",
      title: "Update API Documentation",
      description: "Update Swagger documentation to reflect changes.",
      startDate: "2024-03-18",
      status: "Deferred",
      assignee: "John Doe",
      team: "Web Coder",
      priority: "P1",
    },
    {
      id: "abc123456789",
      title: "Deploy Backend Service",
      description: "Deploy backend to the vercel.",
      startDate: "2024-05-23",
      status: "Deployed",
      assignee: "Michael",
      team: "React",
      priority: "P0",
    },
  ],
  filterData: [],
};
